### ISSUE TITLE
[Enhancement] Add an option to open log files

### ISSUE THREAD

**Issue by Acidham** [BenjaminOddou/alfred-folderify#1]
The end of the workflow will result in a log file being written, and a notification will be shown where the file is being stored. It would be better to show a dialog and ask the user to open the log-file or not. An option in config would be valuable on how the workflow behaves showing the results.

**Comment by BenjaminOddou** [comment]
Hello @Acidham, thanks for the feedback. In the current version, the path is being copied into the clipboard and can be quickly pasted to Alfred to open or show the log file if needed. I can change this behavior by creating an option that will directly open/reveal the log file in finder in the user config panel. I don't really like the idea of adding a dialog because it adds another step.

**Comment by Acidham** [comment]
> I don't really like the idea of adding a dialog because it adds another step.

Agreed, clipboard would also work
